
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harshit Designer
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILLING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(194, 11, 250, 43);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BOOKING NO.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 140, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 80, 152, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"310", null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Room No.", "charge per day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 160, 503, 94);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("TOTAL AMOUNT :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 270, 103, 24);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("GENERATE BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(142, 322, 125, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("PAY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 322, 80, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("3000");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(474, 266, 125, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c423c6d9_z.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 660, 400);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int bno= Integer.parseInt(jTextField1.getText());
String bn= Integer.toString(bno);

if(bn.isEmpty())
JOptionPane.showMessageDialog(this,"ENTER BOOKING NO!!!");
        DefaultTableModel model = (DefaultTableModel)
jTable1.getModel();
try{
    Class.forName("java.sql.DriverManager");
Connection con=(Connection)
DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
Statement stmt=(Statement) con.createStatement();
String query = "SELECT roono,r_d from rate,booking where rate.roomno=booking.roono and bookingno="
        + "'"+bn+"';";
ResultSet rs = stmt.executeQuery(query);
if(rs.next())
{
    bn=rs.getString("bookingno");
    String ch= rs.getString("r_d");
    String ad= rs.getString("A_date)");
    String dd= rs.getString("D_date)");
   Double ad1= Double.parseDouble(ad);
   Double dd1= Double.parseDouble(dd);
   Double total= dd1-ad1;
   Double total1= total+1;
   Double ch1= Double.parseDouble(ch);
   Double ta= total1*ch1;
   jLabel4.setText(""+"Rs."+ta+"/-" );
}
else
    JOptionPane.showMessageDialog(null,"Incorrect Booking No.");
}
catch(Exception e)
{
    JOptionPane.showMessageDialog( this,e.getMessage());
}
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JOptionPane.showMessageDialog(null,"your bill has been paid"); 
        int bno = Integer.parseInt(jTextField1.getText());
String bn = Integer.toString(bno);
int ta0=Integer.parseInt(jLabel4.getText());
String ta = Integer.toString(ta0);
if(bn.isEmpty()) 
    JOptionPane.showMessageDialog(this, "Please enter booking no.!");
else{
    try{
    Class.forName("java.sql.DriverManager");
Connection con=(Connection)
DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
Statement stmt=(Statement) con.createStatement();
String query= "INSERT INTO pay VALUES('"+bn+"','"+ta+"');";
JOptionPane.showMessageDialog(this, "YOUR BILL HAVE BEEN PAYED");


Login l = new Login();
         l.setVisible(true);
         this.setVisible(false);
}
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
        
    }
            }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
